### PR TITLE
Natural scroll emulation is now optional

### PR DESCRIPTION
**Pull request by wookieb**
Please bump to version 1.3.0 after accepting PR :)

### CODE REVIEW

**Comment by vermilion1** [comment]
@basselin any chance to merge this PR?

**Comment by basselin** [comment]
Yes I Do! :)
But I just need a little bit of time.

**Comment by swiety** [comment]
thanks @basselin , appreciated!

**Comment by vermilion1** [comment]
@basselin awesome, thanks :)

**Comment by basselin** [comment]
Version 1.3.0 is added!

**Pull request merged**
